# Generated by Django 6.0.3 on 2026-04-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app_model', '0002_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
