# Generated by Django 4.2.23 on 2026-04-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp_model_learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
